[db]
major_version = 15
port = 54325

[functions.requests]
enabled = true
verify_jwt = true
import_map = "./functions/requests/deno.json"
entrypoint = "./functions/requests/index.ts"

[functions.approve-request]
enabled = true
verify_jwt = true
import_map = "./functions/approve-request/deno.json"
entrypoint = "./functions/approve-request/index.ts"

[functions.reject-request]
enabled = true
verify_jwt = true
import_map = "./functions/reject-request/deno.json"
entrypoint = "./functions/reject-request/index.ts"

[functions.get-programmers]
enabled = true
verify_jwt = true
import_map = "./functions/get-programmers/deno.json"
entrypoint = "./functions/get-programmers/index.ts"

[functions.get-teams]
enabled = true
verify_jwt = true
import_map = "./functions/get-teams/deno.json"
entrypoint = "./functions/get-teams/index.ts"

[functions.create-team]
enabled = true
verify_jwt = true
import_map = "./functions/create-team/deno.json"
entrypoint = "./functions/create-team/index.ts"

[functions.update-team]
enabled = true
verify_jwt = true
import_map = "./functions/update-team/deno.json"
entrypoint = "./functions/update-team/index.ts"

[functions.delete-team]
enabled = true
verify_jwt = true
import_map = "./functions/delete-team/deno.json"
entrypoint = "./functions/delete-team/index.ts"

[functions.get-tasks]
enabled = true
verify_jwt = true
import_map = "./functions/get-tasks/deno.json"
entrypoint = "./functions/get-tasks/index.ts"

[functions.update-programmer]
enabled = true
verify_jwt = true
import_map = "./functions/update-programmer/deno.json"
entrypoint = "./functions/update-programmer/index.ts"

[functions.create-programmer]
enabled = true
verify_jwt = true
import_map = "./functions/create-programmer/deno.json"
entrypoint = "./functions/create-programmer/index.ts"

[functions.delete-programmer]
enabled = true
verify_jwt = true
import_map = "./functions/delete-programmer/deno.json"
entrypoint = "./functions/delete-programmer/index.ts"

[functions.create-task]
enabled = true
verify_jwt = true
import_map = "./functions/create-task/deno.json"
entrypoint = "./functions/create-task/index.ts"

[functions.create-request]
enabled = true
verify_jwt = false
import_map = "./functions/create-request/deno.json"
entrypoint = "./functions/create-request/index.ts"

[functions.get-my-profile]
enabled = true
verify_jwt = true
import_map = "./functions/get-my-profile/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-my-profile/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-my-profile/*.html" ]

[functions.update-my-profile]
enabled = true
verify_jwt = true
import_map = "./functions/update-my-profile/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/update-my-profile/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/update-my-profile/*.html" ]
